# application.yml
server:
  port: 4321

spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: ashok
    password: ashok123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Use 'create-drop' for development, 'update' for production
    show-sql: false  # Set to true for debugging SQL queries
    open-in-view: false  # Disable to avoid the warning
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

# JWT Configuration
jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000  # 24 hours in milliseconds

# Logging Configuration
logging:
  level:
    root: INFO
    hara.userservice: DEBUG
    org.springframework.security: WARN  # Reduce security logging noise
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR  # Disable the specific warning
    org.hibernate.SQL: DEBUG  # Only if you want to see SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Show SQL parameters

# Management endpoints (optional - for monitoring)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized